# <span style="color:green">Install module</span>

## <span style="color:red">pip install termcolor</span>

## Manipulating arrays

# <span style="color:blue"> Importing modules</span>

In [1]:
import numpy as np
from termcolor import colored as cor

###### Let's create a array from 7 to 44 in steps of 3
* <span style="color:green">**command** </span>... np.array
* <span style="color:blue">**np** </span>comes from numpy works as nickname
* <span style="color:blue">**cor** </span>was nickname for colored inside of termcolor module, choose nickname as you like
* **np.array** use array command definition from numpy module
## <span style="color:red">np.array(init, end, step)</span> 

In [2]:
x = np.arange(7,44,3)

print(cor("Set of numbers (array x) every 3 steps from 7 to 44  \n", 'magenta'),x)

Set of numbers (array x) every 3 steps from 7 to 44  
 [ 7 10 13 16 19 22 25 28 31 34 37 40 43]


# Element number (<span style="color:green">Index</span>)

## first element of array has index <span style="color:red">0</span> not 1

In [3]:
print(cor(x[0],'green',attrs=['bold'])," is the value of first array x element ")

print(cor(x[7],'green',attrs=['bold'])," is the value of the seventh element of array x ")


7  is the value of first array x element 
28  is the value of the seventh element of array x 


## Let's recreate the array <span style="color:red">x</span> from <span style="color:green">0 to 64</span>

In [5]:
x = np.arange(0,1024)

print(cor("set of numbers (array) x from 0 to 64 \n", 'magenta'),x)

set of numbers (array) x from 0 to 64 
 [   0    1    2 ... 1021 1022 1023]


## Let's get all values of <span style="color:red">even index</span>

In [10]:
x_even=x[::2] ## PAR
a=x_even
print(cor("Values of elements with even index within array x \n",'magenta'),
      cor(x_even,'blue',attrs=['bold']))

Values of elements with even index within array x 
 [   0    2    4    6    8   10   12   14   16   18   20   22   24   26
   28   30   32   34   36   38   40   42   44   46   48   50   52   54
   56   58   60   62   64   66   68   70   72   74   76   78   80   82
   84   86   88   90   92   94   96   98  100  102  104  106  108  110
  112  114  116  118  120  122  124  126  128  130  132  134  136  138
  140  142  144  146  148  150  152  154  156  158  160  162  164  166
  168  170  172  174  176  178  180  182  184  186  188  190  192  194
  196  198  200  202  204  206  208  210  212  214  216  218  220  222
  224  226  228  230  232  234  236  238  240  242  244  246  248  250
  252  254  256  258  260  262  264  266  268  270  272  274  276  278
  280  282  284  286  288  290  292  294  296  298  300  302  304  306
  308  310  312  314  316  318  320  322  324  326  328  330  332  334
  336  338  340  342  344  346  348  350  352  354  356  358  360  362
  364  366  368  370  372

## Let's get all values of <span style="color:red">odd index</span>

In [11]:
x_odd=x[1::2] ## IMPAR
b=x_odd

print(cor("Values of elements with odd index within array x\n",'magenta'),cor(x_odd,'red',attrs=['bold']))

Values of elements with odd index within array x
 [   1    3    5    7    9   11   13   15   17   19   21   23   25   27
   29   31   33   35   37   39   41   43   45   47   49   51   53   55
   57   59   61   63   65   67   69   71   73   75   77   79   81   83
   85   87   89   91   93   95   97   99  101  103  105  107  109  111
  113  115  117  119  121  123  125  127  129  131  133  135  137  139
  141  143  145  147  149  151  153  155  157  159  161  163  165  167
  169  171  173  175  177  179  181  183  185  187  189  191  193  195
  197  199  201  203  205  207  209  211  213  215  217  219  221  223
  225  227  229  231  233  235  237  239  241  243  245  247  249  251
  253  255  257  259  261  263  265  267  269  271  273  275  277  279
  281  283  285  287  289  291  293  295  297  299  301  303  305  307
  309  311  313  315  317  319  321  323  325  327  329  331  333  335
  337  339  341  343  345  347  349  351  353  355  357  359  361  363
  365  367  369  371  373  

## Please don't make confusion <span style="color:blue">values</span> are not  the <span style="color:red">indexes</span>

In [12]:
print(a,b)

[   0    2    4    6    8   10   12   14   16   18   20   22   24   26
   28   30   32   34   36   38   40   42   44   46   48   50   52   54
   56   58   60   62   64   66   68   70   72   74   76   78   80   82
   84   86   88   90   92   94   96   98  100  102  104  106  108  110
  112  114  116  118  120  122  124  126  128  130  132  134  136  138
  140  142  144  146  148  150  152  154  156  158  160  162  164  166
  168  170  172  174  176  178  180  182  184  186  188  190  192  194
  196  198  200  202  204  206  208  210  212  214  216  218  220  222
  224  226  228  230  232  234  236  238  240  242  244  246  248  250
  252  254  256  258  260  262  264  266  268  270  272  274  276  278
  280  282  284  286  288  290  292  294  296  298  300  302  304  306
  308  310  312  314  316  318  320  322  324  326  328  330  332  334
  336  338  340  342  344  346  348  350  352  354  356  358  360  362
  364  366  368  370  372  374  376  378  380  382  384  386  388  390
  392 

## Values of array x with <span style="color:red"> even indexes</span> in <span style="color:green">reverse order</span>

In [22]:
x = np.arange(0,64)
x_even_reverse=x_even[::-1] ## reverse

print(cor("Reverses the order of values with even indexes within array x \n",'magenta'),
      cor(x_even_reverse,'green',attrs=['bold']))

Reverses the order of values with even indexes within array x 
 [62 60 58 56 54 52 50 48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16
 14 12 10  8  6  4  2  0]


## Get <span style="color:red">size </span>of array x with  <span style="color:green">len </span>command

In [23]:
tamanho=len(x)
print("Size of array x ", cor(tamanho,'red',attrs=['bold']))

Size of array x  64


## Get the <span style="color:red"> first half</span> of <span style="color:green">even indexes</span> array x

## <span style="color:green">Indexes</span>  like to be <span style="color:red"> integer numbers </span> 

In [10]:
metade=int(len(x)/2)
x_even=x[:metade:2] ## 1/2 * PAR

print(cor("Only half of the values with even indexes within array x \n",'magenta'),
      cor(x_even,'blue',attrs=['bold']))

Only half of the values with even indexes within array x 
 [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


## Get the <span style="color:red"> Second half </span> of <span style="color:green">even indexes</span> array x

In [11]:
x_even=x[metade::2] ## 2nd 1/2*PAR

print(cor("Only second half of the values with even indexes within array x \n",'magenta'),
      cor(x_even,'blue',attrs=['bold']))

Only second half of the values with even indexes within array x 
 [32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62]


## Get the <span style="color:red"> Second half </span> of <span style="color:green">even indexes</span> array x times 10

In [12]:
x_even=x[metade::2]*10 ## 2nd 1/2*PAR

print(cor("econd half of the values with even indexes within array x times 10 \n",'magenta'),
      cor(x_even,'blue',attrs=['bold']))

econd half of the values with even indexes within array x times 10 
 [320 340 360 380 400 420 440 460 480 500 520 540 560 580 600 620]


## Get the <span style="color:red"> Second half </span> of <span style="color:green">even indexes</span> array x times -10 + 1

In [13]:
x_even=x[metade::2]*-10+1 ## 2nd 1/2*PAR

print(cor("econd half of the values with even indexes within array x times -10 add 1 \n",'magenta'),
      cor(x_even,'blue',attrs=['bold']))

econd half of the values with even indexes within array x times -10 add 1 
 [-319 -339 -359 -379 -399 -419 -439 -459 -479 -499 -519 -539 -559 -579
 -599 -619]


## Adding new elements  <span style="color:red"> [10, 11, 12]  </span> to array  <span style="color:green">x_even</span> 

In [14]:
x_even = np.append (x_even, [10, 11, 12])

print(cor("Add elements to x_even array \n",'magenta'),
      cor(x_even,'blue',attrs=['bold']))

Add elements to x_even array 
 [-319 -339 -359 -379 -399 -419 -439 -459 -479 -499 -519 -539 -559 -579
 -599 -619   10   11   12]


## Get   <span style="color:red"> last 3  </span> elements of array  <span style="color:green">x_even</span> 

In [15]:
size=len(x_even)
last_3=x_even[size-3:size:1]

print(cor("last 3 elements elements in array x_even \n",'magenta'),
      cor(last_3,'blue',attrs=['bold']))

last 3 elements elements in array x_even 
 [10 11 12]


## Get   <span style="color:red"> and revert, last 3  </span> elements of array  <span style="color:green">x_even</span> 

In [16]:
last_3=x_even[size:size-4:-1]

print(cor("Last 3 elements in array x_even in reverse order ### CAUTION ### \n",'magenta'),
      cor(last_3,'red',attrs=['bold']))

Last 3 elements in array x_even in reverse order ### CAUTION ### 
 [12 11 10]
